config/routes.rb
Rails.application.routes.draw do
  devise_for :users 
  resources :tweets
  get "/articles", to: "articles#index"
  get "/naruto", to: "narutos#index"
  root "home#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :tweets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home
  end
end

app/controllers/narutos_controller.rb
class NarutosController < ApplicationController
  def index
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]
  # GET /tweets or /tweets.json
  def index
    @tweets = Tweet.all

  end

  # GET /tweets/1 or /tweets/1.json
  def show
  end

  def correct_user
    @tweet =  current_user.tweets.find_by(id: params[:id])
    redirect_to tweets_path, notice: "Not Authorize to edit this friend" if @tweet.nil?
  end

  # GET /tweets/new
  def new
    #@tweet = Tweet.new
    @tweet = current_user.tweets.build
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets or /tweets.json
  def create
    #@tweet = Tweet.new(tweet_params)
    @tweet = current_user.tweets.build(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to tweet_url(@tweet), notice: "Tweet was successfully created." }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1 or /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to tweet_url(@tweet), notice: "Tweet was successfully updated." }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1 or /tweets/1.json
  def destroy
    @tweet.destroy

    respond_to do |format|
      format.html { redirect_to tweets_url, notice: "Tweet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:name, :title, :blog, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/narutos_helper.rb
module NarutosHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/articles/index.html.erb
<h1>Articles#index</h1>
<p>Find me in app/views/articles/index.html.erb</p>

app/views/footer/_footer.html.erb
<div class="mt-auto">
  <div class="container">
    <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
      <p class="col-md-4 mb-0 text-muted">© 2021 Company, Inc</p>

      <a href="/" class="col-md-4 d-flex align-items-center justify-content-center mb-3 mb-md-0 me-md-auto link-dark text-decoration-none">
        <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"></use></svg>
      </a>

      <ul class="nav col-md-4 justify-content-end">
        <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Home</a></li>
        <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Features</a></li>
        <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Pricing</a></li>
        <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">FAQs</a></li>
        <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">About</a></li>
      </ul>
    </footer>
  </div>
</div>

app/views/header/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
  <%= link_to "My app", root_path, class:"navbar-brand" %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Home</a>
        </li>

        <li class="nav-item">
          <%= link_to "Naruto", naruto_path, class:"nav-link"%>
        </li>

        <li class="nav-item">
          <%= link_to "Tweets", tweets_path, class:"nav-link"%>
        </li>

        <% if user_signed_in? %>

          <li class="nav-item">
            <%= link_to "Sign Out", destroy_user_session_path, class:"nav-link"%>
          </li>

          <li class="nav-item">
            <%= link_to "Edit Profile", edit_user_registration_path, class:"nav-link"%>
          </li>
        
        <% else %>

          <li class="nav-item">
            <%= link_to "Sign In", new_user_session_path, class:"nav-link"%>
          </li>

          <li class="nav-item">
            <%= link_to "Sign Up", new_user_registration_path, class:"nav-link"%>
          </li>

        <% end %>

      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/home.html.erb
<h1>Welcome to home Page </h1>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
  </head>
  <body>
    <%= render "header/header" %>
    <div class="container">
    <% if notice %>
      <%= render "layouts/alerts" %>
    <% end %>
      <%= yield %>
    </div>
    <%= render "footer/footer" %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
  </body>
</html>

app/views/narutos/index.html.erb
<h1>Narutos#index</h1>
<p>Find me in app/views/narutos/index.html.erb</p>

app/views/tweets/_form.html.erb
<%= form_with(model: tweet) do |form| %>
  <% if tweet.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
        <% tweet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :name, style: "display: block", class:"form-label" %>
    <%= form.text_field :name, class:"form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :title, style: "display: block", class:"form-label"  %>
    <%= form.text_field :title, class:"form-control"  %>
  </div>

  <div class="mb-3">
    <%= form.label :blog, style: "display: block", class:"form-label"  %>
    <%= form.text_area :blog, class:"form-control"  %>
  </div>

  <div class="mb-3" type="hidden">
    <%= form.text_field :user_id, id: :tweet_user_id, value:current_user.id , type: :hidden %>
  </div>

  <div class="mb-3">
    <%= form.submit :Submit, class:"btn btn-outline-dark" %>
  </div>
<% end %>

app/views/tweets/_tweet.html.erb
<div id="<%= dom_id tweet %>" class="card-body">
  <p class="card-title">
    <strong>Name:</strong>
    <%= tweet.name %>
  </p>

  <p class="card-title">
    <strong>Title:</strong>
    <%= tweet.title %>
  </p>

  <p class="card-text">
    <strong>Blog:</strong>
    <%= tweet.blog %>
  </p>

</div>

app/views/tweets/edit.html.erb
<h1>Editing tweet</h1>

<%= render "form", tweet: @tweet %>

<br>

<div>
  <%= link_to "Show this tweet", @tweet, class:"btn btn-outline-primary" %> |
  <%= link_to "Back to tweets", tweets_path, class:"btn btn-outline-info"%>
</div>

app/views/tweets/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Tweets</h1>

<div id="tweets" class="card" style="width: 18rem;" >
  <% @tweets.each do |tweet| %>
    <%= render tweet  %>
    <p>
      <%= link_to "Show this tweet", tweet, class:"btn btn-outline-info" %>
    </p>
    <%= current_user %>
    <%= tweet.user %>

  <% end %>
</div>

<%= link_to "New tweet", new_tweet_path, class:"btn btn-outline-primary" %>

app/views/tweets/new.html.erb
<h1>New tweet</h1>

<%= render "form", tweet: @tweet %>

<br>

<div>
  <%= link_to "Back to tweets", tweets_path, class:"btn btn-outline-primary" %>
</div>

app/views/tweets/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @tweet %>
<br>
<div>
  <% if user_signed_in? %>
   <%= link_to "Edit this tweet", edit_tweet_path(@tweet), class:"btn btn-outline-primary" %> |
  <% end %>
    
  <%= link_to "Back to tweets", tweets_path, class:"btn btn-outline-info" %>
<br>
<br>

   <% if user_signed_in? %>
    <%= button_to "Destroy this tweet", @tweet, method: :delete, class:"btn btn-outline-dark" %>
  <% end %>
</div>